# Generated by Django 4.2.5 on 2024-03-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0007_remove_referral_invited_users_and_more'),
        ('accounts', '0002_user_referral_belongs_to_user_referral_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='refferal.referral'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_referral_info', to='refferal.referral'),
        ),
    ]
