# Generated by Django 4.2.5 on 2024-03-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_referral_belongs_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_belongs_to',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_info',
        ),
    ]
