version: '3'
services:
    db:
        image: postgres:16
        container_name: majors-db
        volumes:
            - ./db/postgres:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - .env
        networks:
            - network

    redis:
        container_name: majors-redis
        ports:
            - 6379:6379
        volumes:
            - ./db/redis:/data
        image: redis:7-alpine
        networks:
            - network

    web:
        restart: always
        build: .
        container_name: majors-web
        command: sh -c "sleep 2 && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        env_file:
            - .env
        volumes:
            - ./app:/app
        depends_on:
            - db
            - redis
        networks:
            - network

    celery:
        container_name: majors-celery
        build:
            context: .
        command: sh -c "celery -A myproject worker --loglevel=info"
        volumes:
            - ./app:/app
        env_file:
            - .env
        depends_on:
            - web
            - redis
        networks:
            - network

networks:
  network:
