version: '3'
services:
    nginx:
        container_name: majors-nginx-refferal
        restart: always
        build: ./nginx/test
        ports:
            - 80:80
        depends_on:
            - web
        networks:
            - network

    db:
        image: postgres:16
        container_name: majors-db-refferal
        volumes:
            - ./db/postgres:/var/lib/postgresql/data/
        ports:
            - 5433:5432
        env_file:
            - .env
        networks:
            - network

    redis:
        container_name: majors-redis-refferal
        ports:
            - 6379:6379
        volumes:
            - ./db/redis:/data
        image: redis:7-alpine
        networks:
            - network

    web:
        restart: always
        build: .
        container_name: majors-web-refferal
        command: sh -c "sleep 2 && gunicorn myproject.wsgi:application -w 4 -b 0.0.0.0:8000"
        ports:
            - 8000:8000
        env_file:
            - .env
        volumes:
            - ./app:/app
        depends_on:
            - db
            - redis
        networks:
            - network

    celery:
        container_name: majors-celery-refferal
        build:
            context: .
        command: sh -c "celery -A myproject worker --loglevel=info"
        volumes:
            - ./app:/app
        env_file:
            - .env
        depends_on:
            - web
            - redis
        networks:
            - network

networks:
  network:
