version: '3'
services:
  db:
    image: postgres:16
    container_name: majors-db
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - .env
    networks:
      - web-network

  redis:
    container_name: majors-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./db/redis:/data
    image: redis:7-alpine
    networks:
      - web-network

  web:
    restart: always
    build: .
    command: sh -c "sleep 2 && 
                    python manage.py migrate --noinput && 
                    gunicorn myproject.wsgi:application -w 4 -b 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app
    networks:
      - web-network

  nginx:
    container_name: majors-nginx
    restart: always
    build: ./nginx/prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - web
    networks:
      - web-network

  celery:
    container_name: majors-celery
    restart: always
    build:
      context: .
    command: sh -c "celery -A myproject worker --loglevel=info"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - web-network

networks:
  web-network:
