# Generated by Django 4.2.5 on 2023-12-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
