# Generated by Django 4.2.5 on 2023-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_completeorder_invoice_id_and_more'),
        ('refferal', '0003_referral_invited_users_referral_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='registrations',
        ),
        migrations.AddField(
            model_name='referral',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='payments', to='payment.order'),
        ),
    ]
