# Generated by Django 4.2.5 on 2024-01-14 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_remove_completeorder_invoice_id_and_more'),
        ('refferal', '0004_remove_referral_registrations_referral_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='complete_payments',
            field=models.ManyToManyField(blank=True, related_name='complete_payments', to='payment.completeorder'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
