# Generated by Django 4.2.5 on 2024-02-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0005_referral_complete_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='complete_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='refferal_percent',
            field=models.FloatField(default=30),
        ),
    ]
