# Generated by Django 4.2.5 on 2024-03-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0006_referral_complete_earnings_referral_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
    ]
