# Generated by Django 4.2.5 on 2024-03-01 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_remove_completeorder_invoice_id_and_more'),
        ('refferal', '0007_remove_referral_invited_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='payments', to='payment.order'),
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
