# Generated by Django 4.2.5 on 2024-03-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0008_referral_invited_users_referral_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
    ]
