# Generated by Django 4.2.5 on 2024-03-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0009_remove_referral_invited_users_remove_referral_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='complete_payments',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='payments',
        ),
    ]
