# Generated by Django 4.2.5 on 2024-03-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0011_alter_referral_complete_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='refferal_percent',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
