# Generated by Django 4.2.5 on 2024-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0012_alter_referral_refferal_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='must_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
