# Generated by Django 4.2.1 on 2023-08-20 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='amount_crypto',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=40),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='currency',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='days',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='email',
            field=models.EmailField(default='jmarkj@mail.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='token',
            field=models.CharField(default='asdfsedfeedfefef', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='type',
            field=models.CharField(default='asfasfswdsdsvd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=40),
        ),
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.IntegerField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='jmarkj@mail.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default='asvcsdvsdvsdv', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='asdcsdvsdvsd', max_length=50),
            preserve_default=False,
        ),
    ]
