# Generated by Django 4.2.1 on 2023-08-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_completeorder_amount_crypto_completeorder_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
