# Generated by Django 4.2.1 on 2023-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_completeorder_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='order_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
