# Generated by Django 4.2.5 on 2024-03-01 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0010_remove_referral_complete_payments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_remove_completeorder_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='completeorder',
            name='referral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_order_referral', to='refferal.referral'),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_complete_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='referral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_referral', to='refferal.referral'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
