# Generated by Django 4.2.5 on 2024-03-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_completeorder_email_remove_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='amount_crypto',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='days',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='token',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='type',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='user',
        ),
        migrations.AddField(
            model_name='completeorder',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payment.order'),
        ),
    ]
