# Generated by Django 4.2.5 on 2024-03-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refferal', '0010_remove_referral_complete_payments_and_more'),
        ('payment', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_referral', to='refferal.referral'),
        ),
    ]
