# Generated by Django 4.2.5 on 2024-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_order_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
