# Generated by Django 4.2.5 on 2024-03-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=150),
        ),
    ]
