# Generated by Django 4.2.5 on 2023-10-31 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLinksHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_info', models.CharField(max_length=150)),
                ('hash_info_ex', models.CharField(max_length=150)),
                ('base_token', models.CharField(max_length=50)),
                ('id_first_token', models.CharField(max_length=50)),
                ('id_second_token', models.CharField(max_length=50)),
                ('id_best_change_exchange', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteTwoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_exchange', models.CharField(max_length=50)),
                ('second_exchange', models.CharField(max_length=50)),
                ('first_give', models.CharField(max_length=50)),
                ('first_get', models.CharField(max_length=50)),
                ('second_give', models.CharField(max_length=50)),
                ('second_get', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteThreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_crypto', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=50)),
                ('best_change_exchange', models.IntegerField()),
                ('id_best_change_give', models.IntegerField()),
                ('id_best_change_get', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
